<!DOCTYPE html>

<html>
  <head>
    <title>About hemanth mahankali</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <link rel="stylesheet" href="assets/css/main.css" />
    <noscript
      ><link rel="stylesheet" href="assets/css/noscript.css"
    /></noscript>
  </head>
  <body class="is-preload">
    <!-- Wrapper -->
    <div id="wrapper">
      <!-- Header -->
      <header id="header">
        <a class="logo">Shiny Porwal</a>
      </header>

      <!-- Nav -->
      <nav id="nav">
        <ul class="links">
          <li><a href="index.html">Projects</a></li>
          <li class="active"><a href="about.html">About Me</a></li>
          <li><a href="work.html">Experience</a></li>
          <li><a href="education.html">Education</a></li>
        </ul>
        <ul class="icons">
          <li>
            <a
              href="https://www.linkedin.com/in/shinyporwal/"
              target="_blank"
              class="icon brands alt fa-linkedin"
              ><span class="label">LinkedIn</span></a
            >
          </li>
          <li>
            <a
              href="https://www.instagram.com/shiny.porwal/"
              target="_blank"
              class="icon brands alt fa-instagram"
              ><span class="label">Instagram</span></a
            >
          </li>
          <li>
            <a
              href="https://github.com/shinyporwal"
              target="_blank"
              class="icon brands alt fa-github"
              ><span class="label">GitHub</span></a
            >
          </li>
        </ul>
      </nav>

      <!-- Main -->
      <div id="main">
        <!-- Box -->

        <div class="box">
          <p>
            Greetings! I am an individual with a rich background in
            Supply Chain Management and Logistics who embarked on an exciting
            journey to expand my horizons. Earning my second Master's degree in
            Information Systems from CSULB, I sought to bridge the gap between
            operational efficiency and cutting-edge technology. My academic
            journey began at Coventry University, where I honed a solid
            foundation in global operations and the intricate nuances of supply
            chain management. However, I felt a compelling urge to delve into
            the realm of information systems, uncovering novel pathways for
            optimization and growth. Embracing this dual academic path, I am
            weaving together a distinctive narrative that interlaces supply
            chain management with information systems. Armed with advanced
            analytical skills and an unwavering enthusiasm for data-driven
            insights, I stand ready to unlock latent potential within intricate
            operational processes. Fuelled by an unyielding commitment to
            continuous learning, I steadfastly remain at the vanguard of
            industry trends and emerging technologies. This positioning empowers
            me to harness the power of data, employ predictive modeling
            techniques, and conceive innovative strategies that equip
            decision-makers to thrive in today's dynamic marketplace. If you are
            in search of a dynamic professional adept at navigating the
            complexities of supply chain management, while adeptly harnessing
            the transformative potential of information systems, I invite you to
            embark on this exhilarating journey alongside me. Together, let's
            script a success story that redefines how organizations operate and
            flourish in the digital age.
          </p>
        </div>
      </div>

      <footer id="footer">
        <section class="split contact">
          <section class="alt">
            <h3>Address</h3>
            <p>Long Beach, California - 90803</p>
          </section>
          <section>
            <h3>Phone</h3>
            <p>(213) 675-2895</p>
          </section>
          <section>
            <h3>Email</h3>
            <p>
              <a href="mailto:shinyporwal@gmail.com" target="_blank"
                >shinyporwal@gmail.com</a
              >
            </p>
          </section>
          <section>
            <h3>Resume</h3>
            <p>
              <a
                id="resumeLink"
                href="/assets/documents/ShinyPorwal_Porwal_Resume.pdf"
                target="_blank"
                >Hire me!</a
              >
            </p>
          </section>
          <section>
            <h3>Social</h3>
            <ul class="icons alt">
              <li>
                <a
                  href="https://www.linkedin.com/in/shinyporwal/"
                  target="_blank"
                  class="icon brands alt fa-linkedin"
                  ><span class="label">LinkedIn</span></a
                >
              </li>
              <li>
                <a
                  href="https://www.instagram.com/shiny.porwal/"
                  target="_blank"
                  class="icon brands alt fa-instagram"
                  ><span class="label">Instagram</span></a
                >
              </li>
              <li>
                <a
                  href="https://github.com/shinyporwal"
                  target="_blank"
                  class="icon brands alt fa-github"
                  ><span class="label">GitHub</span></a
                >
              </li>
            </ul>
          </section>
        </section>
      </footer>

      <!-- Copyright -->
      <div id="copyright">
        <ul>
          <li>&copy; Shiny Porwal</li>
        </ul>
      </div>
    </div>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>
  </body>
</html>
